# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level_date',
            field=models.DateTimeField(null=True),
        ),
    ]
