# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_user_level_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
